stages:
  - build
  - publish

build_linux_64:
  stage: build
  interruptible: true
  artifacts:
    paths:
      - lib/**
    expire_in: 1 day
  before_script:
    - npm install
  script:
    - npm run lint
    - npm run build
    - npm run test
  tags:
  - linux-64
  - node
