stages:
  - build
  - publish

build_linux_64:
  stage: build
  interruptible: true
  artifacts:
    paths:
      - lib/**
    expire_in: 1 day
  before_script:
    - npm install
  script:
    #- npm run lint
    - npm run build
    - npm run test
  tags:
  - linux-64
  - node

publish_gitlab:
  stage: publish
  interruptible: true
  when: manual
  script:
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=https://gitlab.izaber.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//gitlab.izaber.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - >-
      sed 's/\"name\": \"@.*\//\"name\": \"@'${CI_PROJECT_ROOT_NAMESPACE}'\//g' package.json > package.json.new
    - rm package.json
    - mv package.json.new package.json
    - npm version "0.0.${CI_PIPELINE_IID}" --no-git-tag-version
    #- npm publish
  tags:
  - linux-64
  - node
  only:
  - /^(master|test)$/i
